apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi.fullname" . }}
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web-admin-port
      protocol: TCP
      name: web-admin-port
  selector:
    {{- include "unifi.selectorLabels" . | nindent 4 }}
